spring:
  application:
    name: credit-card
  config:
#     import: optional:configserver:https://configserver-jabmm.azurewebsites.net
     import: optional:configserver:http://localhost:8888
        
     
     
